Repository Team-Snacks/backend, pull requests merged in 2022-12, with the labels that each got.

#8 refactor: JWT 토큰에 사용되는 환경변수 변경
  src/main/java/com/snacks/demo/jwt/JwtAuthenticationFilter.java
  src/main/java/com/snacks/demo/jwt/JwtAuthorizationFilter.java
Labels: 코드 개선

#9 fix: 프로젝트 패키지 이름 변경
  src/main/java/com/snacks/backend/BackendApplication.java
  src/main/java/com/snacks/backend/config/CorsConfig.java
  src/main/java/com/snacks/backend/config/EnvConfiguration.java
  src/main/java/com/snacks/backend/config/RedisConfig.java
  src/main/java/com/snacks/backend/config/SecurityConfig.java
  src/main/java/com/snacks/backend/controller/AuthController.java
  src/main/java/com/snacks/backend/controller/UserController.java
  src/main/java/com/snacks/backend/dto/UserDto.java
  src/main/java/com/snacks/backend/entity/User.java
  src/main/java/com/snacks/backend/jwt/JwtAuthenticationFilter.java
  src/main/java/com/snacks/backend/jwt/JwtAuthorizationFilter.java
  src/main/java/com/snacks/backend/jwt/auth/CustomUserDetails.java
  src/main/java/com/snacks/backend/jwt/auth/CustomUserDetailsService.java
  src/main/java/com/snacks/backend/redis/RedisService.java
  src/main/java/com/snacks/backend/repository/AuthRepository.java
  src/main/java/com/snacks/backend/response/CommonResponse.java
  src/main/java/com/snacks/backend/response/ConstantResponse.java
  src/main/java/com/snacks/backend/response/ListResponse.java
  src/main/java/com/snacks/backend/response/ResponseService.java
  src/main/java/com/snacks/backend/response/SingleResponse.java
  src/main/java/com/snacks/backend/response/TokenResponse.java
  src/main/java/com/snacks/backend/service/AuthService.java
  src/test/java/com/snacks/backend/Auth/LoginTest.java
  src/test/java/com/snacks/backend/Auth/SignUpTest.java
  src/test/java/com/snacks/backend/BackendApplicationTests.java
  src/test/java/com/snacks/backend/ConstantTest.java
Labels: 기타

#10 docs: README.md 파일 생성
  README.md
Labels: 문서화

#12 Feat/google 로그인 구현
  .gitignore
  build.gradle
  src/main/java/com/snacks/backend/config/SecurityConfig.java
  src/main/java/com/snacks/backend/controller/AuthController.java
  src/main/java/com/snacks/backend/dto/Role.java
  src/main/java/com/snacks/backend/dto/UserDto.java
  src/main/java/com/snacks/backend/entity/User.java
  src/main/java/com/snacks/backend/jwt/JwtAuthenticationFilter.java
  src/main/java/com/snacks/backend/jwt/JwtAuthorizationFilter.java
  src/main/java/com/snacks/backend/jwt/JwtProvider.java
  src/main/java/com/snacks/backend/oauth/CustomOAuth2UserService.java
  src/main/java/com/snacks/backend/oauth/OAuth2SuccessHandler.java
  src/main/java/com/snacks/backend/oauth/OAuthAttributes.java
  src/main/java/com/snacks/backend/repository/AuthRepository.java
Labels: 기능 추가

#13 fix: 테스트코드 오류 수정
  src/main/java/com/snacks/backend/config/SecurityConfig.java
  src/main/java/com/snacks/backend/controller/AuthController.java
  src/main/java/com/snacks/backend/jwt/JwtAuthenticationFilter.java
  src/main/java/com/snacks/backend/jwt/JwtProvider.java
  src/main/java/com/snacks/backend/oauth/CustomOAuth2UserService.java
  src/test/java/com/snacks/backend/Auth/LoginTest.java
  src/test/java/com/snacks/backend/Auth/SignUpTest.java
Labels: 버그

#14 fix: 자체로그인과 oauth2로그인 충돌 수정
  src/main/java/com/snacks/backend/config/SecurityConfig.java
  src/main/java/com/snacks/backend/controller/AuthController.java
  src/main/java/com/snacks/backend/jwt/JwtAuthenticationFilter.java
  src/main/java/com/snacks/backend/jwt/JwtAuthorizationFilter.java
  src/main/java/com/snacks/backend/jwt/JwtProvider.java
  src/main/java/com/snacks/backend/oauth/CustomOAuth2UserService.java
  src/main/java/com/snacks/backend/oauth/OAuth2SuccessHandler.java
  src/main/java/com/snacks/backend/service/AuthService.java
Labels: 버그

#16 docs: README파일 기술스택 버전 추가
  README.md
Labels: 문서화

#18 feat: 유저 위젯목록 반환
  src/main/java/com/snacks/backend/config/SecurityConfig.java
  src/main/java/com/snacks/backend/controller/UserController.java
  src/main/java/com/snacks/backend/dto/PosDto.java
  src/main/java/com/snacks/backend/dto/SizeDto.java
  src/main/java/com/snacks/backend/dto/UserWidgetDto.java
  src/main/java/com/snacks/backend/dto/WidgetDto.java
  src/main/java/com/snacks/backend/entity/UserWidget.java
  src/main/java/com/snacks/backend/entity/UserWidgetId.java
  src/main/java/com/snacks/backend/entity/Widget.java
  src/main/java/com/snacks/backend/jwt/JwtAuthorizationFilter.java
  src/main/java/com/snacks/backend/repository/UserWidgetRepository.java
  src/main/java/com/snacks/backend/repository/WidgetRepository.java
  src/main/java/com/snacks/backend/service/UserService.java
Labels: 기능 추가

#19 feat: 유저 대시보드에 위젯추가
  src/main/java/com/snacks/backend/controller/UserController.java
  src/main/java/com/snacks/backend/entity/UserWidget.java
  src/main/java/com/snacks/backend/service/UserService.java
Labels: 기능 추가

#20 feat: 유저 위젯 삭제
  src/main/java/com/snacks/backend/controller/UserController.java
  src/main/java/com/snacks/backend/jwt/JwtAuthorizationFilter.java
  src/main/java/com/snacks/backend/repository/UserWidgetRepository.java
  src/main/java/com/snacks/backend/service/UserService.java
Labels: 기능 추가

#21 fix: 유저 위젯 업데이트
  src/main/java/com/snacks/backend/controller/UserController.java
  src/main/java/com/snacks/backend/entity/UserWidget.java
  src/main/java/com/snacks/backend/service/UserService.java
Labels: 기능 추가

#22 feat: 유저 위젯 추가
  src/main/java/com/snacks/backend/controller/UserController.java
  src/main/java/com/snacks/backend/dto/PostUserWidgetDto.java
  src/main/java/com/snacks/backend/service/UserService.java
Labels: 기능 추가

#25 feat: 유저 위젯목록 반환 api에 jwt 연결
  src/main/java/com/snacks/backend/controller/UserController.java
  src/main/java/com/snacks/backend/controller/WidgetController.java
  src/main/java/com/snacks/backend/jwt/JwtAuthorizationFilter.java
  src/main/java/com/snacks/backend/service/UserService.java
Labels: 기능 추가

#32 feat: 유저 위젯 추가 api에 jwt 연결
  src/main/java/com/snacks/backend/controller/UserController.java
  src/main/java/com/snacks/backend/service/UserService.java
Labels: 기능 추가

#33 feat: 유저 위젯 업데이트 api에 jwt 연결
  src/main/java/com/snacks/backend/controller/UserController.java
  src/main/java/com/snacks/backend/service/UserService.java
Labels: 기능 추가

#34 feat: 유저 위젯 삭제 api에 jwt 연결
  src/main/java/com/snacks/backend/controller/UserController.java
  src/main/java/com/snacks/backend/service/UserService.java
Labels: 기능 추가

#35 fix: 같은 이메일이 등록 되어 있을 시 로그인이 안되는 현상
  src/main/java/com/snacks/backend/jwt/auth/CustomUserDetailsService.java
Labels: 버그

#36 fix: 사용하지 않는 환경변수 값을 적용
  src/main/java/com/snacks/backend/controller/AuthController.java
Labels: 버그

#37 feat/실행시-sql-구문-자동실행
  src/main/resources/data.sql
Labels: 기능 추가, 테스트

#40 fix: cors 에러
  src/main/java/com/snacks/backend/config/CorsConfig.java
  src/main/java/com/snacks/backend/config/SecurityConfig.java
  src/main/java/com/snacks/backend/jwt/JwtAuthorizationFilter.java
Labels: 버그

#44 style: 사용하지 않는 import 삭제
  src/main/java/com/snacks/backend/config/CorsConfig.java
  src/main/java/com/snacks/backend/config/SecurityConfig.java
  src/main/java/com/snacks/backend/controller/AuthController.java
  src/main/java/com/snacks/backend/controller/UserController.java
  src/main/java/com/snacks/backend/controller/WidgetController.java
  src/main/java/com/snacks/backend/dto/UserWidgetDto.java
  src/main/java/com/snacks/backend/entity/UserWidget.java
  src/main/java/com/snacks/backend/jwt/JwtAuthenticationFilter.java
  src/main/java/com/snacks/backend/jwt/JwtAuthorizationFilter.java
  src/main/java/com/snacks/backend/jwt/JwtProvider.java
  src/main/java/com/snacks/backend/oauth/CustomOAuth2UserService.java
  src/main/java/com/snacks/backend/oauth/OAuthAttributes.java
  src/main/java/com/snacks/backend/service/UserService.java
  src/main/java/com/snacks/backend/service/WidgetService.java
Labels: 기타
